apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-k8s-web
  labels:
    app: django-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-deployment
  template:
    metadata:
      labels:
        app: django-deployment
    spec:
      containers:
        - name: django-k8s-web
          image: registry.digitalocean.com/cfe-k8s-inventory/django-k8s-web:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: django-k8s-web-prod-env
          ports:
            - containerPort: 8002
              name: gunicorn
      imagePullSecrets:
        - name: cfe-k8s-inventory

---
apiVersion: v1
kind: Service
metadata:
  name: django-k8s-web-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8002
  selector:
    app: django-deployment
